version: '3'

services:
  #  start Postgres
  postgres:
    image: 'postgres:16.2'
    ports:
      - '127.0.0.1:5448:5448'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tryhard
    command: -p 5448

  #  start KeyDB
  keydb:
    image: 'eqalpha/keydb:latest'
    ports:
      - '127.0.0.1:6380:6380'
    restart: always
